// @ts-nocheck
import Head from "next/head";
import styles from "../styles/Home.module.css";
import PolandLists from "../components/Lists/PolandLists";
import { useState, useEffect } from "react";
import { useRouter } from "next/router";
import { motion } from "framer-motion";

import CountryList from "@/components/CountryList/CountryList";

export default function ListsPage() {
  const router = useRouter();
  const { locale } = router;
  const poland =
    (locale == "ua" && "Польща") ||
    (locale == "en" && "Poland") ||
    (locale == "it" && "Polonia") ||
    (locale == "de" && "Polen") ||
    (locale == "ru" && "Польша") ||
    (locale == "pl" && "Polska") ||
    (locale == "hu" && "Lengyelország") ||
    (locale == "cs" && "Polsko") ||
    (locale == "sk" && "Poľsko");

  const [country, setCountry] = useState(poland);
  const [media, setMedia] = useState("");

  useEffect(() => {
    setCountry(poland);
  }, [setCountry, poland, locale]);

  return (
    <>
      <Head>
        <title>Propaganda Diary | Media Lists</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.listCountryWrap}>
        {locale == "ua" && (
          <p className={styles.listsDiscr}>
            Ресурси у білому списку – це якісні джерела, які надають достовірну
            інформацію про зовнішню та внутрішню політику України. Натомість
            джерела з чорного списку регулярно поширюють фейкові наративи про
            Україну.
          </p>
        )}
        {locale == "en" && (
          <p className={styles.listsDiscr}>
            Media on the white list are high-quality media providing reliable
            information about Ukraine’s foreign and domestic policies. On the
            contrary, sources on the black list spread fake news about Ukraine
            on a regular basis.
          </p>
        )}
        {locale == "it" && (
          <p className={styles.listsDiscr}>
            Le risorse nell’elenco bianco sono le fonti di qualità che
            forniscono informazioni affidabili sulla politica estera e interna
            dell&#34;Ucraina. Invece, le fonti inserite nell’elenco nero
            diffondono regolarmente le narrazioni false sull&#34;Ucraina.
          </p>
        )}
        {locale == "de" && (
          <p className={styles.listsDiscr}>
            Die Ressourcen in der weißen Liste sind qualitative Quellen, die
            zuverlässige Informationen über die Außen- und Innenpolitik der
            Ukraine liefern. Stattdessen verbreiten Quellen auf der schwarzen
            Liste regelmäßig gefälschte Narrative über die Ukraine.
          </p>
        )}
        {locale == "ru" && (
          <p className={styles.listsDiscr}>
            Ресурсы в белом списке – это качественные источники, предоставляющие
            достоверную информацию о внешней и внутренней политике Украины. В то
            же время источники из черного списка регулярно распространяют
            фейковые нарративы об Украине.
          </p>
        )}
        {locale == "pl" && (
          <p className={styles.listsDiscr}>
            Zasoby na białej liście są wysokiej jakości źródłami, które
            dostarczają wiarygodnych informacji o polityce zagranicznej i
            wewnętrznej Ukrainy. Zamiast tego źródła z czarnej listy regularnie
            rozpowszechniają fałszywe narracje o Ukrainie.
          </p>
        )}
        {locale == "hu" && (
          <p className={styles.listsDiscr}>
            A fehérlistán szereplő források minőségi források, amelyek
            megbízható információkat szolgáltatnak Ukrajna kül- és
            belpolitikájáról. Ehelyett a feketelistás források rendszeresen
            hamis narratívákat terjesztettek Ukrajnáról.
          </p>
        )}
        {locale == "cs" && (
          <p className={styles.listsDiscr}>
            Zdroje na bílém seznamu jsou kvalitní zdroje, které poskytují
            spolehlivé informace o zahraniční a domácí politice Ukrajiny. Naopak
            zdroje na černé listině pravidelně šíří falešné narativy o Ukrajině.
          </p>
        )}
        {locale == "sk" && (
          <p className={styles.listsDiscr}>
            Zdroje na bielom zozname sú kvalitné zdroje, ktoré poskytujú
            spoľahlivé informácie o zahraničnej a domácej politike Ukrajiny.
            Namiesto toho zdroje na čiernej listine pravidelne šíria falošné
            príbehy o Ukrajine.
          </p>
        )}

        <CountryList
          country={country}
          setCountry={setCountry}
          setMedia={setMedia}
        />
      </div>
      <motion.div
        className={styles.listsPageWrap}
        initial={{ opacity: 0, y: -20 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.3, type: "tween" }}
      >
        <div>
          <PolandLists country={country} />
        </div>
      </motion.div>
    </>
  );
}
